import React from "react";
import image1 from "./images/Picture1.PNG";
import image2 from "./images/Picture2.PNG";
import image3 from "./images/Picture3.PNG";
import image4 from "./images/Picture4.PNG";
import image5 from "./images/Picture5.PNG";
import image6 from "./images/Picture6.PNG";
import image7 from "./images/Picture7.PNG";
import image8 from "./images/Picture8.PNG";

export const DropdownList = () => {
  return (
    <div className="DropdownList">
      <h1 className="padding-Top">Dropdown List</h1>
      <p>
      In order to build a <span className="bold-text">Dropdown List</span>, simply drag and drop the widget into the dashboard work space area.A new window will appear that allows you to customize the list's <span className="bold-text">properties</span>
      <li>
        <span className="bold-text">Properties</span>
      </li>
      <br />
      In this section, you can name and set up a style for the Dropdown List.
      <br />
      Once you lock the position, you will not be able to move the widget in the dashboard area, unless you disable the option again. 
      <br />
       </p>
       <p>
         You can <span className="bold-text">Enable search</span> which allows the user to conveniently find a value in the list.

        Also, you can allow the user to select multiple values resulting to a check box list.

       </p>
       <img src={image1} className="imageClass" />
      <br />
      <p>
      You can build the list containing information based on:
      <br />
      <li>
        <span className="bold-text">Data</span>
      </li>
      <br />
      If you choose this option, the list will be populated with values from a data source which you previously imported in ciPARTHENON. Go to the <span className="bold-text">Data</span> tab and select the data source. Select a column for the labels and optionally, you can select another column as values. You can enable the button Select All and you can label the option accordingly.
      </p>
      <img src={image2} className="imageClass" />
      <br />
      <p>
        <li>
          <span className="bold-text">Custom Entries</span>
        </li>
        If you choose this option, you will have to type in the data. You will find our data editor quite similar to an Excel worksheet. Complete the labels you want to be shown in the list and optionally the values attached to them. In order to add a new row, you have to type the values on the empty line and you will see a new row will be added automatically. You can enable the button Select All and label the option accordingly.
      </p>
      <img src={image3} className="imageClass" />
      <br />
      <p>
        <li>
          <span className="bold-text">Formula Editor</span>
        </li>
        <p>
        If you choose this option, the labels in the list will be generated by a formula. Go to the Data tab and click on f(x). You can learn more about the functions available on the formula editor here.
        </p>
        You can enable the button Select All and you can label the option accordingly.
      </p>
      <img src={image4} className="imageClass" />
      <br/>
      <p>
      Furthermore, you can apply a Default Selection to your list by choosing the <span className="bold-text">first item,specific item or all</span> the items. The list will be automatically filtered by the default selected items when you or another user come back to the dashboard in the edit or view mode.
      </p>
      <p>
        <li>
          <span className="bold-text">Sort & Filter</span>
        </li>
        In this section, you can sort the entries in the list by activating the <span className="bold-text">Sort Series/Values by </span>button. Select the column you want to sort by and the desired order: <span className="bold-text">Ascending , descending , Fixed </span>
      </p>
      <img src={image5} className="imageClass" />
      <p>
      If you want to filter the data shown in the list, click on <span className="bold-text">Add Filter </span>and select the column you want to apply the filter on.
      </p>
      <p>
      You can select your filter based on <span className="bold-text">Data, Formula, Input widget, User parameters or Team parameters.</span>
      <p>
        1.) If you choose <span className="bold-text">Data </span>, you can select between the values existent in the chosen column.
      </p>
      <p>
        2.) If you choose <span className="bold-text">Input widget </span>, you can link the filters (lists) existent in your dashboard to your drop-down list.
      </p>
      <p>
        3.) If you choose <span className="bold-text">Formula Editor </span>, you have to write the syntax by clicking on f(x).
      </p>
      <p>
        3.) If you choose <span className="bold-text">User parameters/Team parameters,</span>you can choose your already defined parameters and restrict the view of the users.
      </p>
      </p>
      <img src={image6} className="imageClass" />
      <br />
      <p>
        <li>
          <span className="bold-text">Format</span>
        </li>
        In this section, you can adjust the appearance of your list by choosing the <span className="bold-text">background color , font , text format ,etc.</span>
      </p>
      <img src={image7} className="imageClass" />
      <br />
      <p>
      <li>
          <span className="bold-text">Interactions</span>
        </li>
        The interaction section allows you to choose the action which will be performed when you double click/hover on the list. You can display a new dashboard, navigate to a URL in a new tab, or display the ToolTip accordingly.
        <p>
        Also, you have the possibility of moving one item to the top of the list once you have selected it. 
        </p>
      </p>
      <img src={image8} className="imageClass" />
      <br />
      
    </div>
  );
};
